language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.9"
install:
    - pip install tox-travis
env:
  global:
    - CC_TEST_REPORTER_ID=
    - CT_URL=http://127.0.0.1:9000
    - CT_TOKEN=abcdef

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - tox
  - pytest --cov=RWAPIMicroservicePython --cov-report=xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
