language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.9"
install:
    - pip install tox-travis
    - pip install pytest-cov
env:
  global:
    - CC_TEST_REPORTER_ID=5099bf6b75276e8ae551224696bb4e8cfc6f624bfa5ed90b3a4d96c74aa6a6c9
    - CT_URL=http://127.0.0.1:9000
    - CT_TOKEN=abcdef

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - tox
after_script:
  - pytest --cov=RWAPIMicroservicePython --cov-report=xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
